CHECK_SUB(CPPMODULE_JSON
    CPPMODULE_FMT
    CPPMODULE_CPPPINYIN
    CPPMODULE_BOOSTCMAKE
    CPPMODULE_BOOSTCMAKE_ENABLE_ALL
    CPPMODULE_TOKENIZERS
    CPPMODULE_UTFCPP
    CPPMODULE_SRELL
    CPPMODULE_LIBSNDFILE
    CPPMODULE_CPPJIEBA
    CPPMODULE_LIBSAMPLERATE
    CPPMODULE_CLD2
    CPPMODULE_XTL
    CPPMODULE_XTENSOR_BLAS
    CPPMODULE_XTENSOR
)
include_directories(${CPPMODULE_ROOTPATH}/gpt_sovits_cpp/include)
add_subdirectory(${CPPMODULE_ROOTPATH}/gpt_sovits_cpp ${CPPMODULE_BINARY_SUBDIR}/gpt_sovits_cpp)
set(CPPMODULE_LINK_LIBRARIES_ALL ${CPPMODULE_LINK_LIBRARIES_ALL} gpt_sovits_cpp_static)
set(CPPMODULE_LINK_LIBRARIES_GPTSOVITSCPP gpt_sovits_cpp_static)