
CHECK_SUB(CPPMODULE_SDL CPPMODULE_FREETYPE2)

include_directories(${CPPMODULE_ROOTPATH}/lvgl)
set(BUILD_SHARED_LIBS OFF)

# 颜色位深度
set(LVGL_CFG_COLOR_DEPTH 32)
# 启用字体支持
set(LVGL_CFG_USE_FREETYPE 1)

# TODO: RTOS可以更换
set(LVGL_CFG_USE_STDLIB LV_STDLIB_CLIB)

# 启用矩阵变换
set(LVGL_CFG_DRAW_TRANSFORM_USE_MATRIX 1)
if (LVGL_CFG_DRAW_TRANSFORM_USE_MATRIX)
  set(LVGL_CFG_USE_MATRIX 1)
  set(LVGL_CFG_USE_FLOAT 1)
endif ()


# 启用SDL绘图后端
set(LVGL_CFG_USE_DRAW_SDL 0)
set(LVGL_CFG_USE_GPU 0)

set(LVGL_CFG_USE_OPENGLES 0)
set(LVGL_CFG_USE_SDL 0)
set(LVGL_CFG_USE_DMA2D 0)

set(LVGL_CFG_USE_SDL 0)
set(LVGL_CFG_USE_X11 0)
set(LVGL_CFG_USE_WAYLAND 0)
set(LVGL_CFG_USE_NUTTX 0)
# Framebuffer
set(LVGL_CFG_USE_LINUX_FBDEV 0)

# 系统支持
set(LVGL_CFG_USE_OS "LV_OS_NONE")
if (WIN32)
  #    set(LVGL_CFG_USE_OS "LV_OS_NONE")
  set(LVGL_CFG_USE_SDL 1)
  #    set(LVGL_CFG_USE_GPU 1)
elseif (ANDROID)
  #    set(LVGL_CFG_USE_OS "LV_OS_NONE")
  set(LVGL_CFG_USE_OPENGLES 1)
  #    set(LVGL_CFG_USE_GPU 1)
elseif (UNIX)
  #    set(LVGL_CFG_USE_OS "LV_OS_PTHREAD")
  set(LVGL_CFG_USE_SDL 1)
  #    set(LVGL_CFG_USE_GPU 1)
elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "STM32")
  #    set(LVGL_CFG_USE_OS "LV_OS_NONE")
  set(LVGL_CFG_USE_DMA2D 1)
elseif (${CMAKE_SYSTEM_NAME} MATCHES "FreeRTOS")
  #    set(LVGL_CFG_USE_OS "LV_OS_FREERTOS")
elseif (${CMAKE_SYSTEM_NAME} MATCHES "RT-Thread")
  #    set(LVGL_CFG_USE_OS "LV_OS_RTTHREAD")
elseif (${CMAKE_SYSTEM_NAME} MATCHES "MQX")
  #    set(LVGL_CFG_USE_OS "LV_OS_MQX")
else ()
  set(LVGL_CFG_USE_OS "LV_OS_NONE")
endif ()


include_directories("${CPPMODULE_ROOTPATH}/lvgl/src")
set(LVGL_CFG_TEMPLATE_HEADER "${CPPMODULE_ROOTPATH}/lvgl/lv_conf_template.h.in")
configure_file(${LVGL_CFG_TEMPLATE_HEADER} "${CPPMODULE_ROOTPATH}/lvgl/lv_conf.h" @ONLY)
configure_file(${LVGL_CFG_TEMPLATE_HEADER} "${CPPMODULE_ROOTPATH}/lvgl/src/lv_conf.h" @ONLY)
add_subdirectory(${CPPMODULE_ROOTPATH}/lvgl ${CPPMODULE_BINARY_SUBDIR}/lvgl)
set(CPPMODULE_LINK_LIBRARIES_ALL ${CPPMODULE_LINK_LIBRARIES_ALL} lvgl::lvgl)
set(CPPMODULE_LINK_LIBRARIES_GPTSOVITSCPP lvgl::lvgl)