
set(EP_SDL_DIR ${CPPMODULE_ROOTPATH}/SDL)
set(SDL_INSTALL_PATH ${CPPMODULE_ROOTPATH}/SDL/install)
set(SDL_BINARY_PATH ${CPPMODULE_ROOTPATH}/SDL)

if (CMAKE_HOST_WIN32)
  #  add_definitions(-DWIN32)
  #  add_definitions(-D_WINDOWS)
  add_definitions(-DUSING_GENERATED_CONFIG_H)
  add_definitions(-D_CRT_SECURE_NO_DEPRECATE)
  add_definitions(-D_NO_CRT_STDIO_INLINE)
  add_definitions(-D_CRT_NONSTDC_NO_DEPRECATE)
  add_definitions(-D_CRT_SECURE_NO_WARNINGS)
  add_definitions(-DSDL_BUILD_MAJOR_VERSION=3)
  add_definitions(-DSDL_BUILD_MINOR_VERSION=1)
  add_definitions(-DSDL_BUILD_MICRO_VERSION=2)
  #  add_definitions(-DCMAKE_INTDIR="${CMAKE_BUILD_TYPE}")
  #  add_definitions(-DDLL_EXPORT)
  set(WINDOWS_STORE OFF)
  set(SDL_LIBC ON)

endif ()
set(SDL_STATIC ON)
set(SDL_SHARED OFF)

add_subdirectory(${CPPMODULE_ROOTPATH}/SDL ${CPPMODULE_BINARY_SUBDIR}/SDL)
string(TOLOWER ${CMAKE_BUILD_TYPE} LOWER_CASE_BUILD_TYPE)
include_directories(${CPPMODULE_BINARY_SUBDIR}/SDL/include-config-${LOWER_CASE_BUILD_TYPE})
include_directories(${CPPMODULE_BINARY_SUBDIR}/SDL/include-config-${LOWER_CASE_BUILD_TYPE}/SDL2)
include_directories(${CPPMODULE_BINARY_SUBDIR}/SDL/include)

set(__CPPMODULE_TEMP_SDL_LIB__ SDL2::SDL2main SDL2::SDL2-static)
if (CPPMODULE_SDL_ENABLE_OPENGL)
  if (OS_IS_WINDOWS)
    set(__CPPMODULE_TEMP_SDL_LIB__ ${__CPPMODULE_TEMP_SDL_LIB__} opengl32.lib Winmm Setupapi Imm32 Version dwmapi legacy_stdio_definitions)
  elseif (OS_IS_APPLE)
    set(__CPPMODULE_TEMP_SDL_LIB__ ${__CPPMODULE_TEMP_SDL_LIB__} OpenGL::GL)
  elseif (OS_IS_LINUX)
    set(__CPPMODULE_TEMP_SDL_LIB__ ${__CPPMODULE_TEMP_SDL_LIB__} X11 GL GLU glut)
  endif ()
endif ()
set(CPPMODULE_LINK_LIBRARIES_ALL ${CPPMODULE_LINK_LIBRARIES_ALL} ${__CPPMODULE_TEMP_SDL_LIB__})
set(CPPMODULE_LINK_LIBRARIES_SDL ${__CPPMODULE_TEMP_SDL_LIB__})
